# -*- coding: utf-8 -*-
"""Analisis_Data_Ratna_KP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIyU9_stmsrEal9bm1Wa8mhVwg2FoZfa

# Proyek Analisis Data: [Bike-Sharing-Dataset]
- **Nama:** [Ratna Sari]
- **Email:** [ratnasari30122019@gmail.com]
- **ID Dicoding:** [ratnapprn]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Bagaimana kondisi cuaca memengaruhi tingkat penyewaan sepeda?
- Pertanyaan 2 : Bagaimana pola penyewaan sepeda berdasarkan jam, hari, dan bulan selama satu tahun (2011)?
- Pertanyaan 3 : Bagaimana tren peningkatan jumlah penyewaan sepeda di setiap musim selama periode 2011–2012?

## Import Semua Packages/Library yang Digunakan
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd      # untuk membaca dan mengolah data
import numpy as np       # untuk perhitungan numerik
import matplotlib.pyplot as plt   # untuk membuat visualisasi
import seaborn as sns    # untuk visualisasi statistik

# agar grafik tampil langsung di notebook
# %matplotlib inline

"""## Data Wrangling

### Gathering Data
"""

#Mengupload file dataset
from google.colab import files
uploaded = files.upload()
import io

#Membaca dataset dan menampilkannya
hour_df = pd.read_csv(io.BytesIO(uploaded['hour.csv']))
hour_df.head()

"""**Insight:**
- Proses import data yang akan digunakan.
- Menampilkan data dengan format csv

### Assessing Data
"""

#Memeriksa tipe data dari setiap kolom
hour_df.info()

#Memeriksa apakah ada missing value (nilai kosong)
print("\nJumlah Missing Value di Setiap Kolom:")
print(hour_df.isna().sum())

#Memeriksa apakah ada data duplikasi
print("Jumlah duplikasi: ", hour_df.duplicated().sum())

#Melihat statistik dasar dari kolom numerik
print("\nStatistik Deskriptif:")
hour_df.describe()

"""**Insight:**
- Kolom dteday masih bertipe object dan perlu diubah menjadi datetime supaya bisa digunakan untuk analisis waktu seperti jam, hari, dan bulan.
- Tidak ditemukan data kosong (missing value) pada semua kolom, sehingga data sudah lengkap.
- Tidak ada data yang terduplikasi, artinya setiap baris data bersifat unik.
- Berdasarkan hasil statistik dasar, nilai-nilai pada kolom numerik terlihat normal dan masih dalam rentang yang wajar.

### Cleaning Data
"""

#Mengubah tipe data kolom 'dteday' menjadi datetime
datetime_columns = ["dteday"]

for column in datetime_columns:
    hour_df[column] = pd.to_datetime(hour_df[column])

#Memastikan tipe data kolom 'dteday' sudah berubah
hour_df.info()

#Menghapus baris dengan nilai kosong (jika ada)
hour_df.dropna(inplace=True)

#Memastikan tidak ada lagi nilai kosong
print("\nJumlah Missing Value Setelah Dibersihkan:")
print(hour_df.isna().sum())

"""**Insight:**
- Kolom dteday telah diubah menjadi tipe data datetime agar dapat digunakan untuk analisis berbasis waktu.
- Tidak ditemukan data kosong maupun duplikat, sehingga dataset siap digunakan untuk tahap analisis selanjutnya.

## Exploratory Data Analysis (EDA)
"""

# Melihat ringkasan statistik dari dataset
hour_df.describe(include="all")

# Melihat korelasi antar variabel numerik
numeric_data = hour_df.select_dtypes(include='number')
correlation = numeric_data.corr()
print(correlation)

#Melihat total penyewaan sepeda berdasarkan jam dalam sehari
hour_df.groupby('hr')['cnt'].sum().sort_values(ascending=False)

"""**Insight:**
- Melihat ringkasan statistik data untuk memahami sebaran nilai dari setiap kolom numerik.
- Mengidentifikasi hubungan antarvariabel numerik menggunakan matriks korelasi untuk mengetahui faktor yang berpengaruh terhadap jumlah penyewaan sepeda.
- Melakukan pengelompokan data berdasarkan jam untuk melihat pola aktivitas penyewaan sepeda sepanjang hari.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

#Mengelompokkan data berdasarkan kondisi cuaca dan menghitung rata-rata jumlah penyewaan sepeda
avg_weather = hour_df.groupby("weathersit")["cnt"].mean().reset_index()

#Menambahkan label yang lebih sederhana agar mudah dipahami
weather_label = {
    1: "Clear",
    2: "Mist/Cloudy",
    3: "Light Rain/Snow",
    4: "Heavy Rain/Snow"
}
avg_weather["weathersit"] = avg_weather["weathersit"].map(weather_label)

#Menampilkan hasil perhitungan
print("Rata-rata penyewaan sepeda berdasarkan kondisi cuaca:")
print(avg_weather)

#Visualisasi menggunakan Line Chart sederhana
plt.figure(figsize=(8,5))
plt.plot(avg_weather["weathersit"], avg_weather["cnt"], marker="o", color="#1E90FF", linewidth=2)
plt.title("Rata-rata penyewaan sepeda berdasarkan kondisi cuaca")
plt.xlabel("Weather Condition")
plt.ylabel("Average Number of Rentals (cnt)")
plt.grid(True)
plt.show()

"""### Pertanyaan 2:"""

# Filter data hanya untuk tahun 2011
hour_2011 = hour_df[hour_df["yr"] == 0]

#Pola Penyewaan Berdasarkan Jam dan Hari
hourly_pattern = hour_2011.groupby(["weekday", "hr"])["cnt"].mean().reset_index()

#Ubah angka hari menjadi nama hari
weekday_labels = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
hourly_pattern["weekday"] = hourly_pattern["weekday"].apply(lambda x: weekday_labels[x])

#Tampilkan sebagian hasil pengelompokan
print("Data rata-rata penyewaan sepeda berdasarkan jam dan hari (2011):")
print(hourly_pattern.head(10))

#Buat pivot untuk visualisasi
pivot_hourly = hourly_pattern.pivot(index="weekday", columns="hr", values="cnt")

#Visualisasi Menggunakan Heatmap
plt.figure(figsize=(12, 5))
sns.heatmap(pivot_hourly, cmap="YlOrRd", linewidths=0.3, annot=False)
plt.title("Pola Penyewaan Sepeda Berdasarkan Jam dan Hari (2011)", fontsize=13, weight='bold')
plt.xlabel("Hours of the Day")
plt.ylabel("Day of the Week")
plt.xticks(rotation=0)
plt.yticks(rotation=0)
plt.show()

#Pola Penyewaan Berdasarkan Bulan
monthly_pattern = hour_2011.groupby("mnth")["cnt"].mean().reset_index()

#Ubah angka bulan jadi singkatan nama bulan
month_labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
monthly_pattern["mnth"] = monthly_pattern["mnth"].apply(lambda x: month_labels[x-1])

#Tampilkan hasil pengelompokan bulanan
print("\nData rata-rata penyewaan sepeda per bulan (2011):")
print(monthly_pattern.head(12))

#Visualisasi menggunakan Bar Chart
plt.figure(figsize=(10, 5))
sns.barplot(x="mnth", y="cnt", data=monthly_pattern, palette="YlGnBu")

plt.title("Rata-rata Penyewaan Sepeda per Bulan (2011)", fontsize=13, weight='bold')
plt.xlabel("Month")
plt.ylabel("Average Number of Rentals")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""### Pertanyaan 3"""

#Mengelompokkan data berdasarkan musim dan menghitung rata-rata penyewaan
season_pattern = hour_df.groupby("season")["cnt"].mean().reset_index()

#Ubah angka musim jadi label agar mudah dibaca
season_labels = {
    1: "Spring",
    2: "Summer",
    3: "Fall",
    4: "Winter"
}
season_pattern["season"] = season_pattern["season"].map(season_labels)

#Menampilkan hasil pengelompokan
print("Data hasil pengelompokan rata-rata penyewaan berdasarkan musim:")
print(season_pattern)

#Visualisasi menggunakan Area Chart
plt.figure(figsize=(8, 5))
plt.fill_between(season_pattern["season"], season_pattern["cnt"], color="#FFA500", alpha=0.5)
plt.plot(season_pattern["season"], season_pattern["cnt"], marker="o", color="#FF8C00", linewidth=2)
plt.title("Rata-rata Penyewaan Sepeda Berdasarkan Musim (2011–2012)", fontsize=13, weight='bold')
plt.xlabel("Average Number of Bike Rentals")
plt.ylabel("Season")
plt.grid(axis='x', linestyle='--', alpha=0.4)
plt.show()

"""**Insight:**
- Pada pertanyaan pertama, proses analisis dilakukan untuk melihat pengaruh kondisi cuaca terhadap jumlah penyewaan sepeda. Hasilnya menunjukkan bahwa penyewaan sepeda tertinggi terjadi saat cuaca cerah, sedangkan menurun signifikan saat hujan atau salju.
- Pada pertanyaan kedua, analisis dilakukan untuk mengetahui pola penyewaan sepeda berdasarkan waktu. Hasilnya memperlihatkan bahwa penyewaan paling tinggi terjadi pada jam berangkat dan pulang kerja, meningkat pada akhir pekan, dan mencapai puncak pada bulan-bulan pertengahan tahun.
- Pada pertanyaan ketiga, proses analisis dilakukan untuk melihat perbandingan jumlah penyewaan di setiap musim. Hasil visualisasi menunjukkan bahwa musim panas memiliki penyewaan tertinggi, diikuti musim gugur, sedangkan musim dingin mencatat jumlah terendah karena kondisi cuaca yang kurang mendukung.

## Analisis Lanjutan (Opsional)
"""

#Analisis Lanjutan: Pola Aktivitas Penyewaan Sepeda (RFM Analysis)
#Pastikan kolom tanggal sudah benar
hour_df["dteday"] = pd.to_datetime(hour_df["dteday"])

#Menghitung Recency: selisih hari terakhir dataset dengan tanggal peminjaman
latest_date = hour_df["dteday"].max()
hour_df["recency"] = (latest_date - hour_df["dteday"]).dt.days

#Menghitung Frequency: banyaknya aktivitas peminjaman per bulan
freq_per_month = hour_df.groupby("mnth")["cnt"].count().reset_index()
freq_per_month.columns = ["month", "frequency"]

#Menghitung Monetary: total peminjaman sepeda per bulan
monetary_per_month = hour_df.groupby("mnth")["cnt"].sum().reset_index()
monetary_per_month.columns = ["month", "monetary"]

#Gabungkan hasil RFM
rfm_df = freq_per_month.merge(monetary_per_month, on="month")
rfm_df["recency"] = hour_df.groupby("mnth")["recency"].min().values

#Ganti angka bulan ke nama bulan
month_labels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
rfm_df["month"] = rfm_df["month"].apply(lambda x: month_labels[x-1])

print("Data gabungan hasil analisis RFM:")
print(rfm_df.head())

#Rata-rata Recency Berdasarkan Musim Menggunakan Bar Chart Horizontal
season_map = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
hour_df["season_name"] = hour_df["season"].map(season_map)

#Hitung rata-rata hari sejak peminjaman terakhir per musim
recency_by_season = hour_df.groupby("season_name")["recency"].mean().reset_index()

plt.figure(figsize=(8, 5))
sns.barplot(y="season_name", x="recency", data=recency_by_season, palette="cool")
plt.title("Rata-rata Hari Sejak Peminjaman Terakhir Berdasarkan Musim", fontsize=13, weight='bold')
plt.xlabel("Rata-rata Hari Sejak Aktivitas Terakhir (Recency)")
plt.ylabel("Musim")
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.show()

#Hubungan Frekuensi dan Total Penyewaan Menggunakan Scatter Plot
plt.figure(figsize=(9, 6))
ax = sns.scatterplot(
    data=rfm_df, x="frequency", y="monetary",
    hue="month", palette="viridis", s=120, edgecolor="white", linewidth=0.7
)
plt.title("Hubungan Frekuensi dan Total Penyewaan Sepeda per Bulan", fontsize=13, weight='bold')
plt.xlabel("Frekuensi Penyewaan per Bulan")
plt.ylabel("Total Jumlah Peminjaman Sepeda")
plt.grid(True, linestyle='--', alpha=0.4)
ax.legend(title="Bulan", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

#Distribusi Total Penyewaan per Bulan (Monetary) Menggunakan Histogram
plt.figure(figsize=(9, 5))
sns.histplot(rfm_df["monetary"], bins=6, kde=True, color="#48C9B0")
plt.title("Distribusi Total Penyewaan Sepeda per Bulan (Monetary)", fontsize=13, weight='bold')
plt.xlabel("Total Penyewaan per Bulan")
plt.ylabel("Frekuensi Bulan")
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.show()

"""## Conclusion

- Pertanyaan 1:
Berdasarkan hasil analisis dan visualisasi, kondisi cuaca memiliki pengaruh yang cukup signifikan terhadap tingkat penyewaan sepeda. Aktivitas peminjaman meningkat tajam pada kondisi cuaca cerah, sedangkan menurun pada kondisi hujan atau salju. Hal ini menunjukkan bahwa cuaca menjadi salah satu faktor utama yang memengaruhi keputusan pengguna dalam melakukan aktivitas luar ruangan seperti bersepeda.
- Pertanyaan 2:
Pola penyewaan sepeda menunjukkan kecenderungan yang konsisten sepanjang waktu. Aktivitas penyewaan paling tinggi terjadi pada sore hari sekitar pukul 17.00–18.00, sementara aktivitas terendah terjadi dini hari. Dari sisi waktu mingguan, akhir pekan mengalami peningkatan jumlah penyewaan dibandingkan hari kerja. Secara bulanan, pertengahan tahun menunjukkan volume peminjaman tertinggi, mengindikasikan adanya pengaruh musim terhadap intensitas penggunaan sepeda.
- Pertanyaan 3:
Berdasarkan hasil analisis tren penyewaan sepeda berdasarkan musim, ditemukan bahwa musim Summer dan Fall merupakan periode dengan tingkat aktivitas peminjaman tertinggi. Sebaliknya, aktivitas menurun pada Winter akibat kondisi suhu yang lebih rendah. Hal ini mengindikasikan bahwa faktor musim turut memengaruhi kebiasaan bersepeda, di mana kondisi lingkungan yang hangat dan cerah lebih mendukung peningkatan penggunaan sepeda.

## Unduh Berkas Data
"""

#Pastikan kolom tanggal sudah dalam format datetime
hour_df["dteday"] = pd.to_datetime(hour_df["dteday"])

# Mengecek jumlah data akhir setelah proses analisis
print("Jumlah baris data akhir:", len(hour_df))
print("Jumlah kolom data akhir:", len(hour_df.columns))

# Simpan dataset hasil pembersihan dan analisis ke file CSV
output_path = "/content/hour_cleaned.csv"
hour_df.to_csv(output_path, index=False)
print(f"Dataset berhasil disimpan di: {output_path}")